# Generated by Django 5.2.7 on 2025-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('artist', models.CharField(max_length=200, verbose_name='Artista')),
                ('album', models.CharField(blank=True, max_length=200, null=True, verbose_name='Álbum')),
                ('genre', models.CharField(max_length=100, verbose_name='Gênero')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
            ],
            options={
                'ordering': ['artist', 'title'],
            },
        ),
    ]
